version: '3'

services:
  app:
    build:
      context: ./app
    container_name: app_node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - code_education_net
    volumes:
      - ./app:/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysql
    networks:
      - code_education_net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - code_education_net
    links:
      - app

networks:
  code_education_net:
    driver: bridge
