version: '3'

services:
  app:
    build:
      context: ./app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - app_db_net
      - app_nginx_net
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=challenge
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    networks:
      - app_db_net

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 8000:80
    networks:
      - app_nginx_net
    depends_on:
      - app

networks:
  app_db_net:
    driver: bridge
  app_nginx_net:
    driver: bridge
